#!/usr/bin/env bash

# Use the flatpak execution wrapper
CHROME="flatpak run com.google.Chrome"
ROFI="/usr/bin/rofi"

emails=("$@")
count=${#emails[@]}

if (( count == 0 )); then
    exit 1
elif (( count == 1 )); then
    $CHROME --profile-email="${emails[0]}" --new-window &
else
    max_lines=10
    lines=$(( count < max_lines ? count : max_lines ))

    selection=$(printf "%s\n" "${emails[@]}" | $ROFI -dmenu -i -p "Select Chrome Profile" -l "$lines")

    if [[ -n "$selection" ]]; then
        $CHROME --profile-email="$selection" --new-window &
    fi
fii
