#!/bin/bash

# Rotate tablet 180°
xsetwacom set "Wacom Intuos S Pen stylus" Rotate half

# Stylus settings (unchanged)
xsetwacom set "Wacom Intuos S Pen stylus" PressureCurve 80 0 100 20
xsetwacom set "Wacom Intuos S Pen stylus" Button 2 2
xsetwacom set "Wacom Intuos S Pen stylus" Button 3 2

# Reversed pad button mapping
xsetwacom set "Wacom Intuos S Pad pad" Button 8 "key +ctrl z -ctrl" 
xsetwacom set "Wacom Intuos S Pad pad" Button 3 "key v"            
xsetwacom set "Wacom Intuos S Pad pad" Button 2 "key e"           
xsetwacom set "Wacom Intuos S Pad pad" Button 1 "key p"          

