# source aliases
source $HOME/.config/zsh/aliases
source $HOME/.config/zsh/variables

# update PATH
export PATH="$HOME/scripts/user:$PATH"
export PATH="$HOME/scripts/shared:$PATH"

# Remove duplicates from the PATH 
export PATH=$(echo $PATH | tr ':' '\n' | awk '!seen[$0]++' | tr '\n' ':')

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v

autoload -Uz compinit
compinit
# End of lines added by compinstall

# prompt
NEWLINE=$'\n'
PROMPT="%n@%m %~${NEWLINE}$ "

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

