# source files
source $HOME/.config/zsh/aliases
source $HOME/.config/zsh/variables
source $HOME/.config/zsh/path

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v

# autocompletion
autoload -Uz compinit
compinit

# prompt
NEWLINE=$'\n'
PROMPT="%n@%m %~${NEWLINE}$ "

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# source node version manager
source /usr/share/nvm/init-nvm.sh
