# ensure tmux uses the same PATH as the shell
set-environment -g PATH "$PATH"
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# turn on vi mode 
set-window-option -g mode-keys vi

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# set custom hotkeys for window navigation
bind a previous-window
bind d next-window

# open new windows in the current directory
bind c new-window -c "#{pane_current_path}"

# open new panes in the current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set-option -g status-left-length 100

# run scripts
# bind f to tmux-sessionizer in tmux
bind f run "tmux neww ~/scripts/shared/tms"
bind ` run "~/scripts/shared/tms ~"

# set theme
source-file ~/.config/tmux/themes/tebby24_theme.conf
