#!/usr/bin/env bash
set -Eeuo pipefail

TARGET_WORD=$(selection_else_clipboard)

PROMPT_FILE="$HOME/.config/chinese-tools/prompt.txt"

PROMPT=$(envsubst < "$PROMPT_FILE")

SENTENCES=$(chinese-tools llm "$PROMPT")

chinese-tools anki add-note Front="$SENTENCES" Back="$TARGET_WORD"
