[anki]
ankiconnect_endpoint = "http://127.0.0.1:8765"
api_version = 6
deck_name = "tebbydeck"
model_name = "tebbycard"

[llm]
model = "deepseek/deepseek-v3.2"

[generation]
sentence_count = 10
delimiter = "|"
